### ISSUE TITLE
评论按钮被隐藏

### ISSUE THREAD

**Issue by zhihaocheng99** [esofar/cnblogs-theme-silence#67]
你好作者,博客下面评论按钮被隐藏
[图片在这](https://images.cnblogs.com/cnblogs_com/codecheng99/1657567/o_2002291215021582978461(1).jpg)可否优化一下

**Comment by WeihanLi** [comment]
之前是好的，应该是最近博客园前端页面改动导致的，可以自己加一个样式

``` css
div.commentform textarea{
  height: 150px;
}
```
