### ISSUE TITLE
页面异常

### ISSUE THREAD

**Issue by Z-Echo** [esofar/cnblogs-theme-silence#68]
在谷歌浏览器中，我尝试了，重置谷歌浏览器以及重装浏览器，但页面评论区任然显示异常，但在windows10自带的edge浏览器中显示正常，可以帮忙查找一下原因吗？
![image](https://user-images.githubusercontent.com/52945898/75670756-53546880-5cb8-11ea-8bc0-e2fc79c941f0.png)

**Comment by Z-Echo** [comment]
对的，我有看到消息区域，有其他人也有这个现象，谢谢！

**Comment by WeihanLi** [comment]
``` css
div.commentform textarea{
  height: 150px;
}
```
